---
# tasks file for kafka
- name: Download Kafka 0.8.2.2
  get_url: >
    url=http://www.eu.apache.org/dist/kafka/0.8.2.2/kafka_2.9.1-{{ KAFKA_VERSION }}.tgz
    dest=/var/
  become: yes

- name: zip
  unarchive: src=/var/kafka_2.9.1-{{ KAFKA_VERSION }}.tgz dest=/var/ copy=no
  become: yes

- name: Rename Unzipped Kafka folder
  shell: mv /var/kafka_2.9.1-{{ KAFKA_VERSION }} /var/kafka
  become: yes
