---
# tasks file for base
- name: Update yum package Manager
  shell: printenv
  become: yes

- name: Install the 'Development tools' package group
  yum: name="@Development tools" state=present
  become: yes

- name: Install Base Packages
  yum: name={{ item }} state=present
  with_items:
  - wget
  - java-1.7.0-openjdk
  - supervisor
  become: yes

- name: Install EPEL 6
  yum: >
    name=http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
    state=present
    disable_gpg_check=yes
  ignore_errors: yes
  become: yes

- name: Install Maven RPM
  shell: wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
  become: yes

- name: Install Maven
  yum: name=apache-maven state=present
  become: yes



